import {
  BarChart3,
  BookOpen,
  Briefcase,
  CalendarDays,
  Camera,
  Clapperboard,
  Coffee,
  HeartPulse,
  LayoutDashboard,
  LayoutList,
  Music,
  Sparkles,
  Star,
  Target,
  Wallet,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { ModuleIconKey } from '../types'

export const MODULE_ICONS: Record<ModuleIconKey, LucideIcon> = {
  dashboard: LayoutDashboard,
  wallet: Wallet,
  calendar: CalendarDays,
  zap: Zap,
  briefcase: Briefcase,
  target: Target,
  book: BookOpen,
  heart: HeartPulse,
  sparkles: Sparkles,
  chart: BarChart3,
  clapper: Clapperboard,
  list: LayoutList,
  star: Star,
  coffee: Coffee,
  music: Music,
  camera: Camera,
}
